/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AdminOrderList` | `/AdminOrderList`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AdminMenuList` | `/AdminMenuList`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AdminCardapioScreen` | `/AdminCardapioScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AdminClienteScreen` | `/AdminClienteScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AdminMenuScreen` | `/AdminMenuScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AdminPedidosScreen` | `/AdminPedidosScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chatbotScreen` | `/chatbotScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LoginScreen` | `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/RegisterScreen` | `/RegisterScreen`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/AdminOrderList` | `/AdminOrderList`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/AdminMenuList` | `/AdminMenuList`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/AdminCardapioScreen` | `/AdminCardapioScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/AdminClienteScreen` | `/AdminClienteScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/AdminMenuScreen` | `/AdminMenuScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/AdminPedidosScreen` | `/AdminPedidosScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chatbotScreen` | `/chatbotScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/LoginScreen` | `/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/RegisterScreen` | `/RegisterScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/AdminOrderList${`?${string}` | `#${string}` | ''}` | `/AdminOrderList${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/AdminMenuList${`?${string}` | `#${string}` | ''}` | `/AdminMenuList${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/AdminCardapioScreen${`?${string}` | `#${string}` | ''}` | `/AdminCardapioScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/AdminClienteScreen${`?${string}` | `#${string}` | ''}` | `/AdminClienteScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/AdminMenuScreen${`?${string}` | `#${string}` | ''}` | `/AdminMenuScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/AdminPedidosScreen${`?${string}` | `#${string}` | ''}` | `/AdminPedidosScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chatbotScreen${`?${string}` | `#${string}` | ''}` | `/chatbotScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/LoginScreen${`?${string}` | `#${string}` | ''}` | `/LoginScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/RegisterScreen${`?${string}` | `#${string}` | ''}` | `/RegisterScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AdminOrderList` | `/AdminOrderList`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AdminMenuList` | `/AdminMenuList`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AdminCardapioScreen` | `/AdminCardapioScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AdminClienteScreen` | `/AdminClienteScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AdminMenuScreen` | `/AdminMenuScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AdminPedidosScreen` | `/AdminPedidosScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chatbotScreen` | `/chatbotScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LoginScreen` | `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/RegisterScreen` | `/RegisterScreen`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
