/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AdminMenuScreen` | `/AdminMenuScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chatbotScreen` | `/chatbotScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LoginScreen` | `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/RegisterScreen` | `/RegisterScreen`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/AdminMenuScreen` | `/AdminMenuScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chatbotScreen` | `/chatbotScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/LoginScreen` | `/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/RegisterScreen` | `/RegisterScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/AdminMenuScreen${`?${string}` | `#${string}` | ''}` | `/AdminMenuScreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chatbotScreen${`?${string}` | `#${string}` | ''}` | `/chatbotScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/LoginScreen${`?${string}` | `#${string}` | ''}` | `/LoginScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/RegisterScreen${`?${string}` | `#${string}` | ''}` | `/RegisterScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AdminMenuScreen` | `/AdminMenuScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chatbotScreen` | `/chatbotScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LoginScreen` | `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/RegisterScreen` | `/RegisterScreen`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
